// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPipePlanner.Data;

#nullable disable

namespace SmartPipePlanner.Data.Migrations
{
    [DbContext(typeof(PlanningDbContext))]
    [Migration("20260116044245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SmartPipePlanner.Data.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("SmartPipePlanner.Data.Element", b =>
                {
                    b.OwnsOne("SmartPipePlanner.Data.Geometry", "Geometry", b1 =>
                        {
                            b1.Property<int>("ElementId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Orientation")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ElementId");

                            b1.ToTable("Elements");

                            b1.WithOwner()
                                .HasForeignKey("ElementId");
                        });

                    b.Navigation("Geometry")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
